### ISSUE TITLE
The native-activity sample application crashes at startup on an Android 6.0 after setting the extractNativeLibs manifest attribute to false

### ISSUE THREAD

**Issue by horaciojcfilho** [android/ndk-samples#668]
**Description**
Setting the **extractNativeLibs** manifest attribute to **false** causes the **native-activity** sample application to crash at statup on an **Android 6.0** device. Unfortunately, I am not being able to find the reason for this issue. It seems to be an **Android 6.0**-specific bug.

**Stacktrace**
```
11-28 11:27:48.377 31847-31847/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.native_activity, PID: 31847
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.native_activity/android.app.NativeActivity}: java.lang.IllegalArgumentException: Unable to find native library: native-activity
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5443)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
     Caused by: java.lang.IllegalArgumentException: Unable to find native library: native-activity
        at android.app.NativeActivity.onCreate(NativeActivity.java:170)
        at android.app.Activity.performCreate(Activity.java:6245)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5443) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
```

**To Reproduce**
- Download the **native-activity** sample application from the [ndk-samples](https://github.com/android/ndk-samples) repository.
- Launch the **Android Studio**.
- Open the **native-activity** project.
- Open the **AndroidManifest.xml** file.
- Set the **extractNativeLibs** manifest attribute to **false**.

**Expected behavior**
The application succeeds to launch.

**Actual behavior**
The application fails to launch due to:
`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.native_activity/android.app.NativeActivity}: java.lang.IllegalArgumentException: Unable to find native library: native-activity`

**Environment:**
- Android Studio 4.0 Canary 4 / Windows 10 May 2019 Update
- Motorola G2 / Android 6.0

**Comment by ggfan** [comment]
There are some other things related to NativeActivity for [Android M and before](https://stackoverflow.com/questions/12524664/cant-load-native-shared-library-with-dependencies-in-a-native-activity-app). Android N added some fixes to make things easier.  This one could be the similar scenario.

Looks like you have added an entry to [buganizer](https://b.corp.google.com/issues/145315585), we would work from that thread and close down this one.

**Comment by horaciojcfilho** [comment]
Hello @ggfan,

Thank you for the reply and the informations provided here and in other bug report channels. Please the reported issue is also triggered by the *bundletool* command line tool that decides to leave the native libraries uncompressed and set the *extractNativeLibs* manifest attribute to *false* if the target device is running Android *6.0* and the application has the *installLocation* manifest attribute set to *internalOnly*. 

To workaround the reported issue, I can force enabling the native libraries compression by specifying a custom *BundleConfig.json* at the moment of building an *Android App Bundle* using the *bundletool* command line tool, but it is going to affect all the Android versions. 

Please I would love if you could endorse the request done in https://github.com/google/bundletool/issues/134. Thank you in advance.

Thankfully,
Horácio Filho

**Comment by ggfan** [comment]
let's work through this with [buganizer](https://b.corp.google.com/issues/145315585): should be able to have a workaround to avoid affecting all OS versions / All apps.

**Comment by horaciojcfilho** [comment]
Hello @ggfan,

Thank you for the feedback and sorry for any inconvenience.

Thankfully,
Horácio Filho

**Comment by ggfan** [comment]
But there is nothing to be sorry for, correct? It is a real problem to be worked out: work will be tracked with [buganizer](https://b.corp.google.com/issues/145315585) item. Thank you for reporting the issue!
