### ISSUE TITLE
how to add a 3rd-party/IMPORTED so file to aar/prefab

### ISSUE THREAD

**Issue by gaoge** [android/ndk-samples#824]
when I try to add a 3rd-party / IMPORTED so to aar/prefab, I got an error like this:

Caused by: java.util.NoSuchElementException: Collection is empty.

	at kotlin.collections.CollectionsKt___CollectionsKt.single(_Collections.kt:592)

	at com.android.build.gradle.internal.tasks.PrefabPackageTask.findLibraryForAbi(PrefabPublishing.kt:248)

	at com.android.build.gradle.internal.tasks.PrefabPackageTask.installLibs(PrefabPublishing.kt:254)

	at com.android.build.gradle.internal.tasks.PrefabPackageTask.createModule(PrefabPublishing.kt:218)

	at com.android.build.gradle.internal.tasks.PrefabPackageTask.doTaskAction(PrefabPublishing.kt:197)

	at com.android.build.gradle.internal.tasks.NonIncrementalTask$taskAction$$inlined$recordTaskAction$1.invoke(BaseTask.kt:63)

	at com.android.build.gradle.internal.tasks.Blocks.recordSpan(Blocks.java:51)

	at com.android.build.gradle.internal.tasks.NonIncrementalTask.taskAction(NonIncrementalTask.kt:94)

My CMakeLists.txt like this:

add_library( # Sets the name of the library.
        mylibrary

        # Sets the library as a shared library.
        SHARED

        # Provides a relative path to your source file(s).
        IMPORTED)

set_target_properties( # Specifies the target library.
        mylibrary

        # Specifies the parameter you want to define.
        PROPERTIES IMPORTED_LOCATION

        # Provides the path to the library you want to import.
        ${CMAKE_CURRENT_SOURCE_DIR}/cmakeLibs/${ANDROID_ABI}/libmylibrary.so

can anyone who can help me? Thanks a lot !

**Comment by DanAlbert** [comment]
Make a second AAR for the imported library. Packages should not ship their dependencies because it causes downstream conflicts.
