### ISSUE TITLE
run app error

### ISSUE THREAD

**Issue by Sean-Tang** [android/ndk-samples#931]
after a import the project step by step, at last, I try to run the app, while it occur a error:
prefab	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:298)
prefab	at com.google.prefab.cli.AppKt.main(App.kt:28)
error when building with cmake using /home/mi/work/ndk-samples/hello-vulkan/app/src/main/cpp/CMakeLists.txt: Build command failed.
Error while executing java process with main class com.google.prefab.cli.AppKt with arguments {--build-system cmake --platform android --abi x86 --os-version 30 --stl c++_shared --ndk-version 25 --output /home/mi/work/ndk-samples/hello-vulkan/app/.cxx/cmake/debug/prefab/x86/prefab /home/mi/.gradle/caches/transforms-3/9fffbb2c02b5d177e49284958e198d58/transformed/jetified-games-activity-1.2.2-alpha01/prefab}

Exception in thread "main" java.lang.IllegalArgumentException: Only schema_version 1 is supported. game-activity uses version 2.
	at com.google.prefab.api.Package.<init>(Package.kt:47)
	at com.google.prefab.cli.Cli$packages$2.invoke(Cli.kt:124)
	at com.google.prefab.cli.Cli$packages$2.invoke(Cli.kt:95)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.google.prefab.cli.Cli.getPackages(Cli.kt)
	at com.google.prefab.cli.Cli.validate(Cli.kt:172)
	at com.google.prefab.cli.Cli.run(Cli.kt:189)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:168)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:16)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:258)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:255)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:273)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:298)
	at com.google.prefab.cli.AppKt.main(App.kt:28)

**Comment by Sean-Tang** [comment]
Hopefully for help!

**Comment by Sean-Tang** [comment]
update AS to the latest, solve this error.
